# permissions for end users to edit ocisecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oci-k8s-resource-sync
    app.kubernetes.io/managed-by: kustomize
  name: ocisecret-editor-role
rules:
- apiGroups:
  - oci-sync.brtrm.de
  resources:
  - ocisecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oci-sync.brtrm.de
  resources:
  - ocisecrets/status
  verbs:
  - get
