---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - oci-sync.brtrm.de
  resources:
  - ocisecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oci-sync.brtrm.de
  resources:
  - ocisecrets/finalizers
  verbs:
  - update
- apiGroups:
  - oci-sync.brtrm.de
  resources:
  - ocisecrets/status
  verbs:
  - get
  - patch
  - update
